---
title: 'Assignment 8: Project and team setup (8 marks)'
output:
    html_document:
        toc: false
---

```{r setup}
knitr::opts_chunk$set(eval = FALSE)
```

*To submit this assignment, upload the full document on blackboard,
including the original questions, your code, and the output. Submit
your assignment as a knitted `.pdf` or `.html` file.*

Prior to beginning this assignment, we suggest you take a look through [this link](https://swcarpentry.github.io/r-novice-gapminder/02-project-intro/index.html) on how to manage project in RStudio using Rprojects. While not a component of this assignment, the tutorial will prove useful as you move forward with your group projects. 

These assignment tasks seem like a lot of work. However, we will be
doing these tasks already during class and during project work. The
purpose of the assignment is for you to get something started on your
final project. While most of these assignment tasks are group based,
please fill out each as an individual. In particular, the first question
should be of *your* forked repository, not one of your team members.
Each team member should submit their *own assignment*.

1.  A new repository has been created for your project on the
    `EEB313-2018` GitHub account. Paste the URL of this forked 
    version below. (0.5 marks)

    -   URL of *your* fork:

2.  Create a `CONDUCT.md` file and open it up in RStudio. Write down
    what you as a team decided on for acceptable conduct/behaviour of
    team members to each other (e.g. "Must be considerate and
    respectful"). Decide who on your team will save this file on their
    forked version of the project. The team member needs to create a
    pull request of this new file to the main project repository (on the
    UofTCoders account). Copy and paste the link to the pull request.
    Every team member must approve this pull request (we will show you
    how to do this in class). Make sure the expectations and behaviours
    are explicit and clear. (1.5 marks)

    -   URL of team member's pull request for `CONDUCT.md`:

3.  A `README.md` file should already exist in your project. Complete
    the following tasks in the README, discussed and written up *as a
    team*. Decide who on your team will save this file on their forked
    version and create a pull request of this file to the main project
    repository. This person should *not* be the same person who did
    task 2. Every team member must approve this pull request. (3.25
    marks)

    -   Create the following headers (make sure to use Markdown headers
        `#`): "Introduction to the project", "Description of the data",
        "Team description", "Installation instructions" (*note*, this
        section we will provide for you).

    -   Fill out the "Introduction to the project" section, answering
        these questions in a paragraph form (don't include these
        questions in the section). What is your project about? What is
        the goal? Why are you doing it?

    -   Fill out the "Description of the data" section, and briefly
        write down what the data is about, what are the variables you
        think you'll use, how the data was collected, and how it will
        answer your research questions. Include a reference of the
        dataset if one is available, for instance:

            Forstmann BU, et al. (2014) Data from: Multi-modal ultra-high resolution
            structural 7-Tesla MRI data repository. Dryad Digital Repository.
            (https://dx.doi.org/10.5061/dryad.fb41s)

    -   Fill out the "Team description" section by writing down a brief
        biography of each member (including what their skills are and
        what their approximate responsibilities (which can change later)
        are for the project) and how team roles will be rotated.

    -   URL of team member's pull request for `README.md`:

4.  Create a folder in your forked repo called `doc/` [**Hint:** See [this link](https://github.com/KirstieJane/STEMMRoleModels/wiki/Creating-new-folders-in-GitHub-repository-via-the-browser) on creating folders from the GitHub editor]. Create a file in the `doc/` 
    folder called `objectives.md`. Create one header (`#` markdown header) 
    called "Study objectives". Create a list (`-` markdown syntax) of each 
    of your research questions that you *as a team* thought of. It doesn't 
    matter what the questions are, how simple, complicated 
    or obvious they are. Just have something written down. These research 
    questions *will* change as you do your analyses. The point is for 
    you to get started thinking about ideas. Decide on another (new) 
    team member to create this file, record it, and make a pull request 
    of this new file. Every team member must approve this pull request. (1 mark)

    -   URL of team member's pull request for `objectives.md`:

5.  Create a file in the `doc/` folder called `analysis-plan.md`. Create
    three headers (`#` markdown headers): "Possible analyses", "Possible
    results tables", "Possible results figures". As a team, discuss and
    record some possible analyses on the data that you could do to
    answer the research questions. Discuss and record possible ways to
    present your results (possible tables, some visualizations). Decide
    on another (new) team member to create this file, record it, and
    make a pull request of this new file. Every team member must approve
    this pull request. *Note:* this analysis and presentation plan does
    **not** have to be accurate, nor do you have to use this later on.
    It could and will (very likely) change. The point is to get you as a
    group thinking about how you will answer the research questions.
    (1.75 marks)

    -   URL of team member's pull request for `analysis-plan.md`:
