---
title: "Final assignment: Scientific report and presentation"
output:
    html_document:
        toc: false
---

## Project description

The course project is a self-directed group data analysis project using real 
ecological data and rigorous scientific methods. Groups are expected to hypothesize
about their chosen data, examine their hypotheses with reproducible and quantitative
analysis techniques, visualize their results, and create scientific products in the
form of a report and a presentation.

You might end up with a publishable scientific product! 
[This paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5210691/) was written by a
group of graduate students as part of the first version of this course, 
which was created by Dr. Christie Bahlai. 

### Data

A list of recommended datasets can be found
[here](https://uoftcoders.github.io/rcourse/lec14-datasets.html#datasets_available_for_use). 
You are welcome to choose a
dataset not listed, or data collected as part of a research project, but keep in mind
that you may not submit anything twice: any work you do as part of this course may not
be submitted for credit in another course (such as a fourth-year research project) and vice versa. 
If choosing a dataset not listed, make sure it is well-documented, legitimate, and 
complex enough to support your analysis efforts. Your work should be original; your
project should not be a reproduction of published analyses. 

### Project deliverables

The following components will be graded as part of the project:

1. Mid-project update (Due Nov. 14):
    * Details for this assignment can be found [HERE](https://uoftcoders.github.io/rcourse/mid-project-update.html).
  
2. Report styled as a journal article, with these or similar sections (more info
below) (Due. Dec. 5):
    * Abstract
    * Introduction / Background and Rationale
    * Methods (with "Data Description" and "Data Analysis" subsections)
    * Results 
    * Discussion 
    * Conclusion
    * Code: project results must be reproducible by someone else
   
3. 10 minute presentation with 2 minutes for questions, styled as a conference
presentation (assume not too much familiarity with the topic in the audience).
The presentations will be held on the last day of class (Dec 3).

While you may not submit your work for this course for credit in another course, you
are welcome to publish or present your work in an academic setting. Groups are
encouraged to publish their work on [figshare](https://figshare.com/), an open, 
citable repository of scientific content. 

### Report guidelines

For the report, you are expected to:

- Search the previous research and literature on your research questions.
- Have clear and explicit objectives and hypotheses.
- Adequately describe and properly cite the data source(s) you will analyze.
- Describe your data analysis in sufficient detail for others to understand what
you did and why.
- Show all the results of your pre-planned data analysis and any additional 
explorations you did.
- Discuss the meaning of your results and how they fit with the previous
literature.

The report and associated code is expected to:

- Be entirely reproducible: You may find
[Rprojects](https://r4ds.had.co.nz/workflow-projects.html) helpful in making
your projects reproducible. Rprojects can be commited to GitHub, allowing anyone
to clone the repo and run your analyses without having to worry about the paths
to all the files being different on their computers. [This
lesson](https://utm-coders.github.io/studyGroup/lessons/misc/project-management-R/lesson/)
on reproducible project management in R may also be helpful.
- Have well documented code: A well documented project will have README files
describing the contents of all folders in your GitHub repos. It will also
contain effective in-line comments in your scripts that showcase the logic of
your analyses and data-wrangling tasks. [This
lesson](https://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R/)
on best practices for writing R code is a good starting place.

You are also expected to work well as a team, and use GitHub to submit and store 
your final product (more details below).

As a *guideline*, aim for at least 2500 words and about 6-8 figures/tables.
*This is **not** a hard criteria*. We are flexible in these *guidelines*, since
we want you to learn to work as a team and create a scientific product. You'll
be surprised how quickly the words, figures, and tables start adding up.

Your code should follow the coding style found [on our resources page](resources.html). 

All items (except the presentation) are due on December 5th at 11:59 pm.

## Project submission

The project report and code should be submitted on GitHub. The report should
also be submitted on Quercus. Each group will have their own GitHub repository
in the [EEB313-2019](https://github.com/eeb313-2019) organization to which you
can upload your report and code. You are welcome to use your GitHub repository
for collaborative work during the project, but feel free to use other tools such
as Google Drive, Dropbox, Overleaf, etc. if you prefer.

## Project grading rubric

|                                                | Inadequate (0 marks)                                                                                                                                                                                          | Adequate (4 marks)                                                                                                                                                | Excellent (8 marks)                                                                                                                                                                    |
|------------|--------------------|--------------------|--------------------|
| Contribution to group work | Student contributed little to project; self-assessed contributions are low in quality and/or quantity; self-assessment is not consistent with actual contribution.                                            | Student contributed adequately to project; made some significant contributions                                                                                    | Student substantially contributed to project to ensure success; self-assessed contributions are crucial to project; self-assessment is consistent with actual contribution. |
| Content                                        | Missing crucial information; methods and results are inconsistent, not logical, or not adequately explained; conclusions are confusing or unsupported by results; unnecessary information included as clutter | Most essential information included; methods and results are adequately described; conclusions supported by results; most included material is relevant to report | All essential information included; methods and results are succinct, clear, logical, and scientifically valid; conclusions are creative and meaningful; project is concise throughout |
| Style and reproducibility                      | Code and writing are poorly organized, poorly formatted, missing units, difficult to read, poorly documented, difficult to reproduce analyses                                                                 | Code and writing are well-organized, well-formatted, consistent use of units and significant figures                                                              | Code and writing are precise and clear throughout, free of errors, well-organized, well-documented, easily reproducible analyses, publication-ready                                    |
| Presentation                      | Presentation is poorly organized; much too long or much too short; presentation is unclear; presentation is missing information; presentation is not scientific and professional; presentation uses too much jargon; not all team members participate; does not adequately address audience questions            | Presentation is adequately organized; timing is appropriate; most information is presented logically; presentation is scientific and professional; most jargon is avoided; all team members participate but equally; audience questions are sometimes addressed well | Presentation is clearly and logically organized; presentation flows and is easy to follow; presentation includes appropriate information without jargon; presentation is well-rehearsed and high-quality; all team members participate equally; audience questions are clearly addressed |

As the final project is a team effort, all members within a group will receive the same mark in the final three categories and an individual mark for their contribution to group work. A final project that is considered to lie between two of the defined levels will be marked accordingly, e.g. between "Adequate" and "Excellent" would be 5, 6, or 7 marks.

