---
title: "More on data visualizations and the Git workflow (plus project work)"
author: Joel Ostblom
---

# Git and GitHub workflow review

First, let's create a chat room for your repository. We will use gitter, since
it has good integrations with GitHub. Got to http://gitter.im/, login with your
GitHub account and click the plus sign to create a new chat room. Browse to
your repository, and add the members of your team. Since your repository is
public, this chatroom will also be public (so you might not want to share
personal information, and keep your discussions on topic, just as if this was
a real-world work project).

Discussions in the chat room are good to crystallize what tasks need to be
tackled next. Once you have identified a specific task, open an issue about it
on GitHub to track the progress of that particular tasks. You should create
issues for your planned analyses, writing, literature review, etc. Then
schedule those into your day and close them when you are done with that task.
It is similar to a powerful task manager for your project. In general, you
should create issues in the main repository, not in your own fork of the
repository. Let's create a new issue based on our discussion, assign the person
we think should work on it, and then review the workflow for addressing the issue.

## Sample workflow for addressing an issue

Let's say we want to create and upload a new file to GitHub. After we have
created the issue for this task, we go about it as follows.

1. Create your own fork of the online Git repository via the GitHub interface.
2. Click the green `Clone or download` button to copy the Git URL.
3. In RStudio, open a new Git project.
    - `File -> Version Control -> Git`. Paste the URL you copied previously and
      select where to save the directory.
4. Click `Create Project`
    - You can now see the new directory if you navigate to it in your file
      navigator.
5. Open a terminal and navigate to the new directory.
    - You could do the navigation in your file browser and then right click to
      open a terminal
        - Right click in the file browser should be enabled by default with
          GitBash on Windows. For Mac's Finder, follow [these
          instructions](https://stackoverflow.com/a/7054045/2166823) (in brief
          `System Preferences > Keyboard > Shortcuts > Services`).
6. In RStudio, click `History` under the small Git button menu.
    - This is similar to typing `git log --oneline --graph` in terminal.
7. Before we add something to this repository, it is good practice to create a
   new branch instead of working on the default master branch. Branches allow
   you to work on features separately and can make it clearer what is what when
   merging your code with others.
    - This is the only step that *has to* to be done from the command line.
      Navigate to the directory just created via RStudio and type `git checkout
      -b <branchname>` to create and switch to a new branch. You can also switch
      branches in RStudio via a dropdown menu.
8. Create a new text file in RStudio and add some text.
9. Save the file locally in the Git directory that you created via RStudio.
    - These changes are not saved into your Git history until you explicitly
      tell Git to save them.
10. Before saving (committing) into the Git repository, click `Diff <filename>`
   in the RStudio Git menu, to see the differences between your current working
   directory and what you have saved in the Git repository since previously.
    - This would be the same as typing `git diff <filename>` in the terminal.
11. The differences are what we expect, so let's click `Stage` (either the
   checkbox or the button).
    - This would be the same as typing `git add <filename>` in terminal (adding
      the file to the "staging area".
12. Now we can commit our changes, which means saving them into our local Git
   repository. Add a commit message and click `Commit`.
    - This would be the same as typing `git commit <filename> -m 'Your commit
      message here'` in terminal.
    - The reason you are staging first and then committing, instead of just
      "saving" in one step, is that this workflow gives more power and
      more flexibility. For example, it allows you to stage partial changes from a
      file or changes from several files and then commit them together as one
      commit because they are addressing the same issue.
13. You can now see your commit in the `History` tab (might need to press
   refresh). You might also notice that your forked GitHub repository online
   (`origin`) is one commit behind your local Git repo. This is because we have
   not uploaded our changes yet.
    - Remember that `origin` is just an alias (nickname) on your computer to
      the URL of your online Git storage location (GitHub in this case), so
      that you don't have to type the full URL each time. You could have called
      this anything, but `origin` is the convention.
14. To upload the changes to your fork, press `Push Branch` in the Git menu.
    - This would be the same as typing `git push` in terminal.
    - Refresh your history to see that all the branches are now on the same
      commit.
15. Finally you want to suggest that the changes from our fork are included in
   the main repository. This is where your collaborators come back into the
   picture. You want to request that whoever has control over the main
   repository reviews your changes and pulls them into the main repository if
   they look good.
    - This is usually done via the GitHub.com interface. If you go to the main
      repository or your fork, you will see a link has popped up that asks you
      to perform a pull request (PR).
16. After the code has been pulled into the main repository (merged) you can
   close the issue!
    - You could also have closed the issue via the PR directly, by adding
      `'close #<issue_number>'` to the commit message (in this case `close #1`).

Done!

One additional note to save you some potential headaches (also called merge
conflicts...). If you are not working from a Git repository that you just
cloned, you should make sure that the master branch of your local fork of the
repository, is up to date with the latest commit on the master branch of the
main repository, before you create a new branch. Put another way: if someone
else has made changes to the main repository, you want those in your fork before
you start working on new features.

If you type `git remote -v` inside your repository, you will see that it
currently only has one remote (online storage location) specified, which is your
fork with the alias `origin`. To add the main repository, go to its GitHub page
and click the green button `Clone or download`, copy the URL, and pasted into
this command `git remote add upstream <pasted_url>`. The name `upstream` is a
convention, and it will be the alias to this URL. Now you can sync your local
master branch with the upstream master branch: `git pull upstream/master
master`. These changes (and any other changes you add) will be uploaded to your
fork's GitHub location next time you push.
