---
title: "Preparing a scientific item for academic publishing"
---
## Lesson preamble

> ### Lesson objectives:
>
> - Understand the roles and responsibilities surrounding authorship
> - Learn about current conventions around academic publishing and how they
>   are changing with open access journals and preprint servers
>
> ### Lesson outline:
>
> - Authorship (25 min)
>     - Different types of contributors (10 min)
>     - How to credit data and software creators? 10 min)
>     - ORCID for keeping track of a scientist's contributions (5 min)
> - Academic Publishing (40 min)
>     - An overview of the peer review system (10 min)
>     - How do you decide where to publish? (10 min)
>     - Moving away from impact factors (10 min)
>     - Video: Open Access Explained! (10 min)
> - Submitting a Scientific Publication (35 min)
>     - General format (10 min)
>     - Journal specifications (10 min)
>     - I've submitted, now what? (5 min)
>     - General writing tips (10 min)
----

*The following has been adapted from [Lecture 3 of the original RQM
course](https://cbahlai.github.io/rqm-template/lessons/week3/)*

## Authorship

### Different Types of Contributors

What kind of contributions make someone an author of a scientific publication?
Here are some common types of contributions:

- Concept framework and question
- Funding
- Research design
- Data collection
- Analysis
- Writing and manuscript preparation
- Editing
- Manuscript submission and revision handling


This will vary from field to field. Consider the following:

- Is doing only one of these enough to merit authorship?
- If not, then what in your opinion is the relative weight of each of these?

**Tip:** Have discussions about authorship early! If you're concerned
about how your contributions will be recognized, it is always best to have
talked about these issues with all those involved early on, rather than when
everything is done and it's about time to submit.

#### Further Reading

- A great overview of authorship with a focus on ecology:
    - [Determining authorship for a peer-reviewed scientific publication](https://arthropodecology.com/2012/08/31/determining-authorship-for-a-peer-reviewed-scientific-publication/) by Chris Buddle.
- An article in Science Magazine about [authoship conventions](http://www.sciencemag.org/careers/2010/04/conventions-scientific-authorship)
- A paper about [gender disparity in authorship](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0066212)

### How to Credit Data and Software Creators?

As researchers in all sorts of fields begin to fruther embrace scripting and
releasing their analyses and code, there are some challenges faced with authorship
and citation. Let's discuss some interesting questions:

- Why is there a discrepancy between the way credit is offered to data
and software creators compared to ?
- Are data and software research products?
    - Who 'owns' the data that is produced, and what does this ownership entail?
- What is the best way to credit data and software creators?

### ORCID

An [ORCID](https://orcid.org/) is a unique identifier that can distinguish you
from other researchers (useful if you have a common name!) and has been
integrated into many different aspects of the research workflow from
manuscript/grant submission and citation listings.

## Academic Publishing

### An Overview of the Peer Review System

- What is peer review?
- Why do we rely on peer review to publish our science?
    - Filtering manuscripts for publication from an editorial perspective
    - Making constructive suggestions to improve manuscripts, and science overall
    - But this is all in an ideal world...
- What challenges arise through use of the peer review process?
    - Does mandatory double-blinding of reviewers and reviewees help?
    - What about publishing the names of reviewers along with publications?
- What criteria do you think a new or improved system for reviewing science would need?

#### The Scientific Life Cycle

Broadly speaking, the life cycle of scientific publications entailst the following:

1. Research (new findings are interpreted and reported upon)
2. Peer Review (these reports are reviewed by a number of field 'experts')
3. Publication (if they pass through the review process, they go through production)
4. Dissemination & Preservation (these items are copied, archived for posterity)
5. Reuse & Citation (other scientists make use of these finding to inform further
    research, or the information becomes part of general knowledge as time passes)
6. Return to #1 (the cycle goes on...)

(Adapted from [Berkeley Library Publishing Lifecycle](http://www.lib.berkeley.edu/scholarly-communication/publishing/publishing-lifecycle))

### How Do You Decide Where to Publish?

- Think about journals in your field that you would like to publish to, and
let's discuss what factors contribute to these choices

When choosing where to publish, it used to be convention to use some variation
of "Choose the journal with the highest impact factor that also fits your work".
However, with increasing discussion about issues surrounding open access,
this makes the decision difficult. Submission costs, review process, whether the
journal is open access and how the journal is viewed by your colleagues (especially
by decision makers...) all play into the final decision.

#### Moving Away from Impact Factors

Journal impact factors are a measure of the average number of citations articles
from that journal have received over a period of a year. How we value science
and scientists has been dominated in the past by the impact factors of the
journals they publish their work as a proxy for the quality of their papers.

Questions:

- Is this the right way for us to be determining the quality of research?
- And if not, what is the right way to value science and in turn, scientists
behind the research?

You can read [this article](http://www.nature.com/news/beat-it-impact-factor-publishing-elite-turns-against-controversial-metric-1.20224)
in Nature about pushback against impact factors from influential players in
scientific publishing.

#### Preprint Servers

While the definition may vary, for our purposes, we will define a preprint as
a research article, review or body of scientific work that has yet to be published in a journal.

- Do you have any hesitations about submitting to a preprint server?

### Video: Open Access Explained! (8:23)

<iframe width="420" height="315" src="https://www.youtube.com/embed/L5rVH1KGBCY" frameborder="0" gesture="media" allowfullscreen></iframe>
Fake or non-existent impact factors.

### The ethics and risks in sharing data

‘Scooping’ is often cited as a concern when discussing sharing data. However,
getting scooped from a published data source has been [empirically demonstrated](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002432)
to be a rare phenomenon, but even some open advocates have had trouble supporting
[blanket open data policies](https://emckiernan.wordpress.com/2014/02/26/my-concerns-about-ploss-new-open-data-policy/).

Let's discuss the following:

- Which concerns about data/code sharing do you feel have merit?
- How can we mitigate these issues?

## Submitting a Scientific Publication

Now that we have a good idea of authorship and the scientific publication process,
let's consider the steps you would take to actually submit a scientific item for
publishing.

### General Format

Typically, a research article will contain the following sections:

- “Background and Rationale”
- “Research Objectives and Hypotheses”
- “Methods”
- “Results”
- “Discussion”
- “Conclusion”

Do these look familiar? They should, because they are the headings you need to
include in your final assignment! "Background and Rationale" and "Research
Objectives and Hypotheses" are usually combined into one "Introduction" section,
but this varies from journal to journal. Also, the order may vary with some
placing the detailed methods in the supplementary. Journals may also require
a short "Significance Statement" as to why the finding is interesting. This may
be more common in basic science that has clinical/translational implications.
Also, many journals also require a written abstract for their work as well.

### Journal Specifications

Depending on what journal you decide to publish in, you may have to change
the format to meet these guidelines. This may include:

- word counts (either for sections or the whole document)
- section headings
- figure and figure caption formats
- methods formats
- reference styles (this is where those .csl + .bib files come in handy!)
- statistical information

Often, you will also need to write a **cover letter** to discuss the importance of
your work, and why it is appropriate for the journal in question. This helps give
editors more context for why they should consider your work for their journal.

### I've submitted, now what?

This is what it will typically look like after you've submitted to a journal,
however, specific timelines and details will of course vary from journal to journal.
For example, there may be multiple rounds of revision, or you may need to appeal a decision in some cases. Please look up the submission process for your journal of interest
for more information.

1. Editors will decide whether or not to send out your manuscript for reviews
2. Reviewers will be contacted and if they agree to review, they will receive
a deadline to send in their comments on what other experiments or discussion
points would improve the manuscript, and ultimately, whether they are in
favour of publishing this work
3. Depending on the reviews, you may be rejected at this point, or need to make
revisions which may entail more experiments, different statistical analyses, or
clarifying the findings to address the comments of the reviewers.
4. The revised manuscript will be sent back to reviewers to again decide if they
should suggest the editor to publish the paper or not.
5. The editor makes a final decision, if it is a rejection, they may suggest
submission to a different journal, and/or some brief description as to why
they will not proceed with the manuscript.
6. If your article has been accepted, the production phase begins where you will
work with the editor to make your manuscript publication ready.

### General Scientific Writing Tips

Scientific writing is very structured. After reading many articles, you will
begin to see the patterns emerge from author to author. You may even start to
pick out the good writers from the bad writers, and take away good practices
from the good writers. While there is no simple recipe, there are guidelines
you can follow.

These are some tips on the writing process and style:

- Be clear and concise, especially when stating your objectives/hypotheses
- Define your terms: don't use acronyms without first defining them,
- Jargon should be minimized, and explained if they must be used
- Typically, do not state a fact without citing work that supports this fact.
While you may think something is obvious, not everyone reading your work will.
- Edit, Edit, Edit. You should plan in advance to have others read your work if
possible, but your first draft should not be your last draft
    - Have someone who is not in your field read over your work. While the details
    of specific terms (which you should be minimizing) may not be clear to a
    non-expert, they should still be able to understand the big picture.

In terms of content, these are some questions you can ask yourself:

- Do you give context as to why your research question is interesting?
- Do you clearly state what your findings are?
- Do you give perspective on how your findings fit in (or don't fit in) with
accepted views, or existing literature?
- Do you address other experiments and interesting questions that result from
your findings?
